Feature/autonomous
sneakysnakesfrc/robot-2021 pull request #15
Opened 2021-02-15 21:53 UTC by OVEYMTarik57

PathABlue, PathARed, PathATogether orbital were added and their codes were written. Extra codes fixed. Also some code is added to Robot.java. @vatanaksoytezer

2021-03-28 17:18 UTC, vatanaksoytezer requested changes

2021-03-28 17:18 UTC, vatanaksoytezer commented on src/main/java/frc/robot/Robot.java
> +    m_robotContainer.m_robotDrive.m_odometry.resetPosition(new Pose2d(0,0, null), new Rotation2d(0));
Trajectory'ler 0,0 dan başlamıyor. Hangi trajectory çalıştırılacaksa ona uygun ekilde pozisyon resetlenmeli.

2021-03-28 17:18 UTC, vatanaksoytezer commented on src/main/java/frc/robot/SneakyTrajectory.java
> +  public Trajectory[] PathARed = new Trajectory[2];
Barrel ve Bounce görevlerinin Trajectoryleri yapılmamış

2021-03-28 17:18 UTC, vatanaksoytezer commented on src/main/java/frc/robot/SneakyTrajectory.java
> +            10);
Şu 10'u constants dosyasında parametre yapalım, ismi kMaxAutoVoltage olsun

2021-03-28 17:18 UTC, vatanaksoytezer commented
Yukarıda gerekli değişiklikleri belirttim onlar dışında gayet temiz görünüyor elinize sağlık, bunları düzenleyince mergeleyelim @KahramanAkyuz @OVEYMTarik57

2021-03-28 17:33 UTC, OVEYMTarik57 commented on src/main/java/frc/robot/SneakyTrajectory.java
> +            10);
Bitti

2021-03-28 18:30 UTC, OVEYMTarik57 commented on src/main/java/frc/robot/Robot.java
> +    m_robotContainer.m_robotDrive.m_odometry.resetPosition(new Pose2d(0,0, null), new Rotation2d(0));
Bitti

2021-07-01 15:34 UTC, emrecandabak commented
ben bir baktım da "trajectory 0,0 dan başlamıyor" dediğimiz kısımda yapılan fix hatalı gibi duruyor. zaten pozisyon sıfırlarken bir de 0,0'da olacak şekilde yeni path tanımlamış tarık biraz anlamsız buldum. onun dışında o kMaxAutoVoltage kısmı düzgün duruyor. Barrel ve bounce hala yok. @OVEYMTarik57

2021-07-02 17:00 UTC, OVEYMTarik57 commented
Koddaki bazı kötü görünen kısımaları okunabilir hale getirdim. "trajectory 0,0 dan başlamıyor" kısmını düzelttim. Ayrıca Barrel ve Bounce'un trajectorylerini ekleyip otonom komutlarını yaptım. Extra belki Barrelın daha doğru çalışması için pointer eklenilebilir fakat onun haricinde bir sıkıntı göremedim. Sende istersen bir kontrol edebilirsin @emrecandabak

2021-07-03 18:34 UTC, emrecandabak commented
Şu an düzgün duruyor, eline sağlık. Main'e mergeliyorum.

2021-07-03 18:34 UTC, merged